### ISSUE TITLE
Focus Timer

### ISSUE THREAD

**Issue by JayaPK21** [maijako/focus-pilot#1]
# Focus Timer

## User Story

As a busy person who is working on a task that requires deep focus and concentration,
I want an app that lets me set personalized work time blocks,
So that I could focus on a task in hand

## Acceptance Criteria

GIVEN the focus time application,
WHEN I select the button to start the study timer,
THEN the application should start the study timer

**Comment by maijako** [comment]
Basic timer functionality now meets the acceptance criteria
