### ISSUE TITLE
Timer Toggle Button with Stop Confirmation

### ISSUE THREAD

**Issue by JayaPK21** [maijako/focus-pilot#39]
# Timer Toggle Button 

## User Story

As a user of the Pilot application,
I want to be able to use a single button for the timer,
So that I can use the same button to start and stop the timer.

## Acceptance Criteria

GIVEN the Pilot application website,
WHEN the button to start the timer is clicked,
THEN the button toggles to a stop timer button. 

GIVEN the main timer in Pilot application is running,
WHEN the button to stop the timer is clicked,
THEN the application shows a confirmation message to stop the timer, and the button is toggled to start button once confirmation is received.

**Comment by dodzikojo** [comment]
Feature added
