### ISSUE TITLE
Suggestion List Display

### ISSUE THREAD

**Issue by JayaPK21** [maijako/focus-pilot#4]
# Suggestion List Display

## User Story

As an application user,
I want to see a list of suggestions displayed at the end of study time,
So that I can choose what needs to be done during break time.

## Acceptance Criteria

GIVEN the focus timer is running during the study time,
WHEN the study time comes to an end,
THEN the user can see a list of options that is displayed, for them to select from.

**Comment by maijako** [comment]
@JayaPK21 are you happy for me to close this issue as it is no longer relevant?

**Comment by JayaPK21** [comment]
Ok we can close this issue. Will need to create another one for displaying the meditation option in the middle.
