### ISSUE TITLE
Stop-timer

### ISSUE THREAD

**Issue by maijako** [maijako/focus-pilot#40]
## User Story
As a user of the Pilot app,
I want my Start Timer button to change to Stop Timer when I start the timer
So that I have the ability to re-set the timer

## Acceptance Criteria
GIVEN the Pilot application timer,
WHEN the Start Timer button is clicked
THEN the Stop Timer button appears that clears the timer

**Comment by JayaPK21** [comment]
I am assigning this bug to myself to link the stop button to clearing the timer.
