### ISSUE TITLE
Timer Controls Display

### ISSUE THREAD

**Issue by JayaPK21** [maijako/focus-pilot#5]
# Timer Controls Display

## User Story

As an application user,
I want to be able to control my work/study time,
So that I can choose the required time accordingly for the specific project.

## Acceptance Criteria

GIVEN the pilot website,
WHEN I see the timer controls panel on the landing page,
THEN I am able to edit the times required for my project before starting the pomodoro timer.

**Comment by dodzikojo** [comment]
I have created a branch "left-panel-layout" to address this issue.
