### ISSUE TITLE
News update Pop-up

### ISSUE THREAD

**Issue by JayaPK21** [maijako/focus-pilot#7]
# News update Pop-up

## User Story

As a pilot web application user,
I want to see a pop-up of the latest news updates at the end of study time, 
So that I can catchup on the latest news that I missed during study time.

## Acceptance Criteria

GIVEN the focus timer is running on the application,
WHEN the timer runs out,
THEN a pop up is displayed on the website showing the latest news updates to be read.

**Comment by dodzikojo** [comment]
completed
